# Generated by Django 6.0.2 on 2026-02-19 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('manager', 'Менеджер'), ('support', 'Техническая поддержка'), ('other', 'Другое')], default='other', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ContactsPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Контакты', max_length=255)),
                ('description', models.TextField(blank=True)),
                ('telegram_channel_url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Страница контактов',
                'verbose_name_plural': 'Страница контактов',
            },
        ),
        migrations.CreateModel(
            name='DepositsPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Депозиты', max_length=255)),
                ('big_text', models.TextField()),
                ('total_deposits', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Страница депозитов',
                'verbose_name_plural': 'Страница депозитов',
            },
        ),
        migrations.CreateModel(
            name='ExampleLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_type', models.CharField(choices=[('site', 'Сайт'), ('bot', 'Бот')], max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Пример ссылки',
                'verbose_name_plural': 'Примеры ссылок',
                'ordering': ['link_type', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FaqItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'FAQ пункт',
                'verbose_name_plural': 'FAQ пункты',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FaqPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='FAQ', max_length=255)),
                ('intro_text', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Страница FAQ',
                'verbose_name_plural': 'Страница FAQ',
            },
        ),
        migrations.CreateModel(
            name='FeatureBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='marketing/features/')),
                ('show_on_home', models.BooleanField(default=True)),
                ('use_telegram_channel_link', models.BooleanField(default=False)),
                ('telegram_link_label', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Блок преимуществ',
                'verbose_name_plural': 'Блоки преимуществ',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(max_length=255)),
                ('hero_subtitle', models.CharField(max_length=255)),
                ('hero_cta_text', models.TextField()),
                ('available_currencies', models.CharField(max_length=255)),
                ('features_title', models.CharField(default='Преимущества', max_length=255)),
                ('example_sites_title', models.CharField(default='Примеры сайтов', max_length=255)),
                ('example_bots_title', models.CharField(default='Примеры ботов', max_length=255)),
            ],
            options={
                'verbose_name': 'Главная страница',
                'verbose_name_plural': 'Главная страница',
            },
        ),
        migrations.CreateModel(
            name='RoadmapItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status_label', models.CharField(blank=True, max_length=100)),
                ('planned_date', models.DateField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Пункт roadmap',
                'verbose_name_plural': 'Пункты roadmap',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RoadmapPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Roadmap', max_length=255)),
                ('intro_text', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Страница roadmap',
                'verbose_name_plural': 'Страница roadmap',
            },
        ),
        migrations.CreateModel(
            name='ServiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ServicesPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Услуги', max_length=255)),
                ('intro_text', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Страница услуг',
                'verbose_name_plural': 'Страница услуг',
            },
        ),
        migrations.CreateModel(
            name='DepositForum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forum_name', models.CharField(max_length=255)),
                ('forum_url', models.URLField()),
                ('deposit_amount', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forums', to='marketing.depositspage')),
            ],
            options={
                'verbose_name': 'Форум с депозитом',
                'verbose_name_plural': 'Форумы с депозитами',
                'ordering': ['order', 'id'],
            },
        ),
    ]
