# Generated by Django 6.0.2 on 2026-02-22

import django.utils.timezone
from django.db import migrations, models


def migrate_roadmap_item_data(apps, schema_editor):
    RoadmapItem = apps.get_model("marketing", "RoadmapItem")
    for item in RoadmapItem.objects.all():
        raw_label = (item.status_label or "").strip()
        normalized = raw_label.lower()

        if normalized in {"done", "completed", "выполнено", "сделано"} or "выполн" in normalized:
            status = "DONE"
        elif "план" in normalized or "plan" in normalized or "в работе" in normalized or "work" in normalized:
            status = "PLANNED"
        else:
            status = "PLANNED"

        date_label = ""
        if item.planned_date:
            date_label = item.planned_date.strftime("%Y-%m-%d")
        elif raw_label and normalized not in {"done", "planned"}:
            if "план" not in normalized and "plan" not in normalized and "выполн" not in normalized:
                date_label = raw_label

        item.status = status
        item.date_label = date_label
        item.save(update_fields=["status", "date_label"])


class Migration(migrations.Migration):

    dependencies = [
        ("marketing", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="roadmapitem",
            options={
                "ordering": ["status", "order", "id"],
                "verbose_name": "Пункт roadmap",
                "verbose_name_plural": "Пункты roadmap",
            },
        ),
        migrations.RenameField(
            model_name="roadmapitem",
            old_name="description",
            new_name="text",
        ),
        migrations.AddField(
            model_name="roadmapitem",
            name="status",
            field=models.CharField(
                choices=[("DONE", "DONE"), ("PLANNED", "PLANNED")],
                default="PLANNED",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="roadmapitem",
            name="date_label",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="roadmapitem",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="roadmapitem",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="roadmapitem",
            name="text",
            field=models.TextField(),
        ),
        migrations.RunPython(migrate_roadmap_item_data, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="roadmapitem",
            name="planned_date",
        ),
        migrations.RemoveField(
            model_name="roadmapitem",
            name="status_label",
        ),
    ]
