# Generated by Django 6.0.2 on 2026-02-22 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_update_roadmap_item_schema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roadmapitem',
            name='status',
            field=models.CharField(choices=[('DONE', 'Выполнено'), ('PLANNED', 'Запланировано')], default='PLANNED', max_length=10),
        ),
    ]
