# Generated by Django 6.0.2 on 2026-02-22 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0003_alter_roadmapitem_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RoadmapPage',
        ),
    ]
