# Generated by Django 6.0.2 on 2026-03-01 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0004_delete_roadmappage'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPGeoCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('country_code', models.CharField(blank=True, max_length=2)),
                ('country_name', models.CharField(blank=True, max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'IP гео-кеш',
                'verbose_name_plural': 'IP гео-кеш',
                'ordering': ['-updated_at', 'ip_address'],
            },
        ),
        migrations.CreateModel(
            name='VisitEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('country_code', models.CharField(blank=True, max_length=2)),
                ('country_name', models.CharField(blank=True, max_length=100)),
                ('path', models.CharField(max_length=255)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('visited_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Посещение',
                'verbose_name_plural': 'Посещения',
                'ordering': ['-visited_at'],
                'indexes': [models.Index(fields=['visited_at'], name='marketing_v_visited_fa5c58_idx'), models.Index(fields=['country_code'], name='marketing_v_country_20e4d3_idx'), models.Index(fields=['ip_address', 'path', 'visited_at'], name='marketing_v_ip_addr_a939a6_idx')],
            },
        ),
    ]
