# Generated by Django 6.0.2 on 2026-03-01 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0005_ipgeocache_visitevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='examplelink',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='marketing/example_links/'),
        ),
    ]
